// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAahGvi_kkE2_xgMSlcyk9rS7coXptPX_k',
    appId: '1:899675298466:web:713ca3d23e26d3fb8c55fb',
    messagingSenderId: '899675298466',
    projectId: 'peliculas-78eb5',
    authDomain: 'peliculas-78eb5.firebaseapp.com',
    storageBucket: 'peliculas-78eb5.appspot.com',
    measurementId: 'G-BDE750YLKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkSSh6lHBt4YhoO1s6WJDZswlRiNi1HRE',
    appId: '1:899675298466:android:f3372aaeede62b778c55fb',
    messagingSenderId: '899675298466',
    projectId: 'peliculas-78eb5',
    storageBucket: 'peliculas-78eb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPpFR2QqXjgF4Zn-sxn3uhBJxwrGQk-LQ',
    appId: '1:899675298466:ios:b148f448e66cd4418c55fb',
    messagingSenderId: '899675298466',
    projectId: 'peliculas-78eb5',
    storageBucket: 'peliculas-78eb5.appspot.com',
    iosBundleId: 'com.bimsina.movies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPpFR2QqXjgF4Zn-sxn3uhBJxwrGQk-LQ',
    appId: '1:899675298466:ios:b148f448e66cd4418c55fb',
    messagingSenderId: '899675298466',
    projectId: 'peliculas-78eb5',
    storageBucket: 'peliculas-78eb5.appspot.com',
    iosBundleId: 'com.bimsina.movies',
  );
}
